[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "simple-httpfs"
version = "0.4.12"
description = "A simple FUSE filesystem for reading http files"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Peter Kerpedjiev", email = "pkerpedjiev@gmail.com"}
]
requires-python = ">=3.7"
dependencies = [
    "boto3",
    "diskcache",
    "fusepy",
    "requests",
    "slugid",
    "tenacity"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/higlass/simple-httpfs"
Repository = "https://github.com/higlass/simple-httpfs"

[project.scripts]
simple-httpfs = "simple_httpfs.__main__:main"
